export interface FestivalDto {

    /*
    A festival has several informations : 

    id : number generated by the back end
    name : string 
    location : string
    startDate : Date
    endDate : Date
    //TODO  :  PricingZones : dictionnary {name of the zone : (ZoneTarifDTO}
    //TODO : logo : string (url of the logo)
    */
    id? : number, 
    name : string
    location : string
    start_date : Date
    end_date: Date
    table_count : number
    big_table_count: number
    town_table_count : number
}
