export interface FestivalDto {

    /*
    A festival has several informations : 

    id : number generated by the back end
    name : string 
    location : string
    startDate : Date
    endDate : Date
    PricingZones : dictionnary {name of the zone : (ZoneTarifDTO}
    */
    id? : number, 
    name : string
    location : string
    startDate : Date
    endDate: Date
}
