services:
    db:
        image: postgres:16-alpine
        container_name: ayae-festival_db_prod
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
           - ./backend/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
           - ./backend/db/editorsData.csv:/tmp/editorsData.csv  
           - ./backend/db/typesOfGamesData.csv:/tmp/typesOfGamesData.csv  
           - ./backend/db/GamesDATA.csv:/tmp/GamesDATA.csv 
           - db_data:/var/lib/postgresql/data
        networks:
            - secure_net
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 30
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: ayae-festival_backend_prod
        restart: unless-stopped
        depends_on:
            db:
                 condition: service_healthy
        env_file:
            - .env
        environment:
            NODE_ENV: production
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        volumes:
            - ./backend/certs:/app/certs:ro
            - uploads_data:/app/uploads
        ports:
            - "4000:4000"
        networks:
            - secure_net

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: ayae-festival_frontend_prod
        restart: unless-stopped
        depends_on:
            - backend
        ports:
            - "8080:80"
        networks:
            - secure_net
    adminer:
        image: adminer:latest
        container_name: ayae-festival_adminer_prod
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "8081:8080"
        environment:
            - ADMINER_DEFAULT_SERVER=db
        networks:
            - secure_net
volumes:
    db_data:
    uploads_data:
networks:
    secure_net:
